language: python
python:
- 3.6
- 3.5
install:
- sudo apt-get update
- pip install -U tox-travis
before_install:
- openssl aes-256-cbc -K $encrypted_9a11d91e3f1f_key -iv $encrypted_9a11d91e3f1f_iv
  -in .env.enc -out .env -d
script: tox
